
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: test
  annotations:
    backstage.io/kubernetes-id: test
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: fmenesesg/test
    dapr.io/application-id: test
    argocd/app-name: 'test'
spec:
  type: website
  system: system:default/conference-application
  lifecycle: production
  owner: group:default/guests
